name: callback_controller

description: Controls the call frequency of a callback and exposes a stream
  that emits the controller state.

version: 0.0.1

homepage: https://github.com/simphotonics/callback_controller

topics:
  - callback
  - debounce
  - stream
  - controller

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
