name: callback_controller

description: Controls the call frequency of a callback and exposes a stream that
  emits the controller state.

version: 0.0.2

homepage: https://github.com/simphotonics/callback_controller

topics:
  - callback
  - debounce
  - throttle
  - stream
  - controller

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
